setting:
  name: "test_spidey_sense_gs"
  output_root: "./spidey-sense-experiments-as-is/"
  pc_path: "./data/spidey-sense/selected-sequences/2025-08-08-10-driving-sequence-02/pointclouds"
  pose_path: ""
  calib_path: "./data/spidey-sense/all_sensor_extrinsics_param.yaml"
  imu_path: "./data/spidey-sense/selected-sequences/2025-08-08-backpack-sequence-02/2025-08-08-backpack-sequence-02_imu_data.csv"
  imu_calib_path: "./data/spidey-sense/xsens_analysed.yaml"
  deskew: True
process:
  use_inertial_deadreconing: False
  use_adptive_downsampling: False
  min_range_m: 1.0
  max_range_m: 80.0
  min_z_m: -10.0
  vox_down_m: 0.06
  dynamic_sdf_ratio_thre: 0.8
sampler:
  surface_sample_range_m: 0.25
  surface_sample_n: 6
  free_sample_begin_ratio: 0.5
  free_sample_end_dist_m: 0.6
  free_front_sample_n: 3 
neuralpoints:
  voxel_size_m: 0.2
  search_alpha: 0.5
  feature_dim: 32
  color_feature_dim: 16
  weighted_first: False
  query_nn_k: 6
  search_alpha: 0.2
decoder:
  freeze_after_frame: 30
loss:
  main_loss_type: bce
  sigma_sigmoid_m: 0.05
  weight_color: 0.0
  ekional_loss_on: True
  numerical_grad: False
  weight_e: 0.2
  loss_weight_on: True
  dist_weight_scale: 0.8
continual:
  batch_size_new_sample: 1000
  pool_capacity: 2e7
  pool_filter_freq: 1
tracker:
  source_vox_down_m: 0.4
  iter_n: 100
pgo:
  pgo_freq_frame: 20
  context_cosdist: 0.3
optimizer: # mapper
  iters: 15  # iterations per frame for sdf mapping
  batch_size: 16384
eval:
  mesh_freq_frame: 10 # reconstruct the mesh every x frames
  mesh_min_nn: 15
  o3d_vis_on: True # visualize the mapping or not
  silence_log: True # output the logs or not