continual:
  batch_size_new_sample: 1000
  pool_capacity: 2e7
  pool_filter_freq: 1
decoder:
  freeze_after_frame: 30
eval:
  mesh_freq_frame: 10
  mesh_min_nn: 15
  o3d_vis_on: false
  silence_log: true
loss:
  dist_weight_scale: 0.8
  ekional_loss_on: true
  loss_weight_on: true
  main_loss_type: bce
  numerical_grad: false
  sigma_sigmoid_m: 0.05
  weight_color: 0.0
  weight_e: 0.2
neuralpoints:
  color_feature_dim: 16
  feature_dim: 32
  query_nn_k: 6
  search_alpha: 0.2
  voxel_size_m: 0.2
  weighted_first: false
optimizer:
  batch_size: 16384
  iters: 15
pgo:
  context_cosdist: 0.3
  pgo_freq_frame: 20
process:
  dynamic_sdf_ratio_thre: 0.8
  max_range_m: 80.0
  min_range_m: 1.0
  min_z_m: -10.0
  use_adptive_downsampling: false
  use_inertial_deadreconing: true
  vox_down_m: 0.06
sampler:
  free_front_sample_n: 3
  free_sample_begin_ratio: 0.5
  free_sample_end_dist_m: 0.6
  surface_sample_n: 6
  surface_sample_range_m: 0.25
setting:
  calib_path: ./data/spidey-sense/all_sensor_extrinsics_param.yaml
  deskew: false
  imu_calib_path: ./data/spidey-sense/xsens_analysed.yaml
  imu_path: ./data/spidey-sense/selected-sequences/2025-08-08-backpack-sequence-04/2025-08-08-backpack-sequence-04_imu_data.csv
  name: '"spidey-spense-2025-08-08-backpack-sequence-04"'
  output_root: ./spidey-sense-experiments-with-inertial/
  pc_path: ./data/spidey-sense/selected-sequences/2025-08-08-backpack-sequence-04/pointclouds
  pose_path: ''
tracker:
  iter_n: 100
  source_vox_down_m: 0.4
